### ISSUE TITLE
Unable to install from pypi

### ISSUE THREAD

**Issue by kvdb** [fnl/patricia-trie#2]
```
$ pip -V
pip 1.5.6 from /tmp/foo/local/lib/python2.7/site-packages (python 2.7)

$ pip install patricia-trie
Downloading/unpacking patricia-trie
  Downloading patricia-trie-9.tar.gz
  Running setup.py (path:/tmp/foo/build/patricia-trie/setup.py) egg_info for package patricia-trie
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/foo/build/patricia-trie/setup.py", line 4, in <module>
        with open('README.rst') as file:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

 File "<string>", line 17, in <module>

  File "/tmp/foo/build/patricia-trie/setup.py", line 4, in <module>

    with open('README.rst') as file:

IOError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by fnl** [comment]
fixed with a47f0b7698fe60a6a3a657ca899fbd89d17c0c09
(version = 10)
